### PR TITLE
fix: migrate conflictpicker to NcDialog and remove incorrect semantic closing icon

### LINKED ISSUE #1095: [a11y] Close button is not clickable when ConflictPicker is opened
See: https://github.com/nextcloud/server/pull/43667#issuecomment-1955752207

It seems that the close button on the ConflictPicker is not currently accessible with a mouse cursor. It does seem related to its z-index, so I will investigate this ASAP!

### PR DESCRIPTION
**Pull request by emoral435**
Resolves #1095

**Summary**
* Before, the ConflictPicker was built using NcModal. This is good, but migrating to NcDialog will allow for more features if needed in the future, and we also can remove the "x" button
* The reason this PR was opened was because we could not click it, but after looking more into it, I do not believe that the conflict picker should have it. Previously, it did not even close the modal anyways (it would open it again), and semantically, because a conflict is happening, I believe that the user should choose between a file, or ignore importing the file.

**Video**

https://github.com/nextcloud-libraries/nextcloud-upload/assets/110193237/0c1c5e86-ef57-44a1-bf9f-dc21e16a3ef1

### CODE REVIEW

File: lib/components/ConflictPicker.vue [hunk 1]
```diff
@@ -372,7 +373,7 @@ export default Vue.extend({
 		position: sticky;
 		z-index: 10;
 		top: 0;
-		padding: var(--margin);
+		padding: 0 var(--margin);
```
Comment (emoral435) [inline lib/components/ConflictPicker.vue:376]: lessen the padding for the header, as without this, the header has more padding than previously and looks really bloated

File: lib/components/ConflictPicker.vue [hunk 2]
```diff
@@ -1,7 +1,8 @@
 <template>
-	<NcModal class="conflict-picker"
+	<NcDialog class="conflict-picker"
 		data-cy-conflict-picker
 		:close-on-click-outside="false"
+		:canClose="false"
```
Comment (Pytal) [inline lib/components/ConflictPicker.vue:5]:
```suggestion
		:can-close="false"
```

**Review by skjnldsv — APPROVED** [review]
:rocket:

**Review by Pytal — APPROVED** [review]
Thanks!

File: lib/components/ConflictPicker.vue [hunk 3]
```diff
@@ -1,7 +1,8 @@
 <template>
-	<NcModal class="conflict-picker"
+	<NcDialog class="conflict-picker"
```
Comment (susnux) [inline lib/components/ConflictPicker.vue:2]: `NcDialog` **requires** the `name` prop for accessibility reasons (a11y labeling).
So put the `name` into the `name` prop and remove the `h2` from the header below.

```suggestion
	<NcDialog class="conflict-picker"
		:name="name"
```

Comment (emoral435) [reply lib/components/ConflictPicker.vue:2]: Ahhh, good catch. Added :) The view after the changes:
image

**Comment by emoral435** [comment]
Cypress seems related

File: lib/components/ConflictPicker.vue (hunk 3 above)
Comment (susnux) [reply lib/components/ConflictPicker.vue:2]: are you sure this is after the changes? Because I would expect the title to be placed on the top centered.

Comment (emoral435) [reply lib/components/ConflictPicker.vue:2]: image
You where right 😅 New screenshot here ^

**Comment by skjnldsv** [comment]
@emoral435 this broke a feature.
Now we cannot cancel an upload.

The close icon was used to know if the user wanted to stop the process entirely.
There are two buttons:
1. One to skip the conflicts, but it will still upload the files that you selected and are _NOT_ conflicting
2. The continue button, to continue after resolving the conflicts (and proceed to the initial upload)

I will fix it in a followup and add a third dedicated cancel button

**Comment by emoral435** [comment]
> @emoral435 this broke a feature.
Now we cannot cancel an upload.

Ahh, I see. I will check out the PR you mention in the comment, but thank you for the catch! :)
