### PR TITLE
fix(uploader): Make sure every request is added to the job queue

### LINKED ISSUE #1323: Folder upload can overload server with requests
The new option to upload a folder seems to be potentially a trigger for causing performance issues.

I noticed that selecting a folder like our company handbook with tons of files to it issues lots of requests and blocks all available resources on my dev setup. However it seems after the initial PROPFIND/MKCOL flood the individual file uploads with PUT are properly throttled so that only a couple are executed at the same time.

Just briefly looking at the code i think we should introduce another pqueue for https://github.com/nextcloud-libraries/nextcloud-upload/blob/main/lib/uploader.ts#L302

cc @susnux since you worked on that iirc :)

### PR DESCRIPTION
**Pull request by susnux**
* Resolve #1323 

## Summary

Remove the hack with the concurrency of the job queue, instead refactor the directory creation:
1. Add it to the upload queue (to track progress)
2. Add the request to the job queue
3. Wait for parent to be created -> continue with children

## Screen shots

Note that for demonstration purpose I limited the concurrency to **3** and throttled the network.

[Bildschirmaufnahme_20240813_165415.webm](https://github.com/user-attachments/assets/7d0985e8-e794-462c-a328-c88330b32eb2)

---

*Sorry for the big diff, but some refactoring needed to get rid of some of my hacks* :sweat_smile:

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
I think this broke the conflict upload

File: lib/uploader.ts [hunk 1]
```diff
@@ -234,40 +234,88 @@ export class Uploader {
...
+				const promise = this.uploadDirectory(destination, rootFolder, callback, davGetClient(this.root))
+				// Make sure to cancel it when requested
+				onCancel(() => promise.cancel())
+				// await the uploads and resolve with "finished" status
+				const uploads = await promise
+				upload.status = UploadStatus.FINISHED
+				resolve(uploads)
+			} catch (error) {
+				logger.error('Error in batch upload', { error })
+				upload.status = UploadStatus.FAILED
```
Comment (skjnldsv) [inline lib/uploader.ts:260]: This broke the cancellation detection.
https://github.com/nextcloud/server/blob/b06f5ba4c47450f355a8903c1a93ac68e8c6cfc2/apps/files/src/views/FilesList.vue#L658-L661

Comment (skjnldsv) [reply lib/uploader.ts:260]: https://github.com/nextcloud-libraries/nextcloud-upload/pull/1614
